### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by caseyhoward**
Eliminate needing to use gulp.series with only one task.

### CODE REVIEW

**Comment by phated** [comment]
This example doesn't work

**Comment by caseyhoward** [comment]
Ah, my bad. Sorry about that.

**Comment by caseyhoward** [comment]
It works if you call build or assign the result of gulp.series to a variable directly. I'm not sure how much better that is than what's already there though.

On a side note, I noticed while testing this that if I have a task that runs the same function as my default task and I define it after my default task, when I run gulp without a task name it says "Starting 'whatever'" instead of "Starting 'default'". Is this the expected behavior?

**Comment by caseyhoward** [comment]
For example:
```js
var build = gulp.series('build');
gulp.task('default', build);
gulp.task('a', build);
```

**Comment by phated** [comment]
that's interesting.  not sure what would be causing that

**Pull request closed without merging**
