### PR TITLE
Updating recipes to align with new docs

### PR DESCRIPTION
**Pull request by S1SYPHOS**
Let me know if migrating over some / all of the recipes is something you are interested in.

### CODE REVIEW

**Comment by phated** [comment]
The recipes really need to be deleted.  They are a massive disappointment.  #2164 is our epic that outlines that they all need to go away or be completely rewritten.

**Comment by S1SYPHOS** [comment]
True. I wanted to kickoff a complete rewrite, but since it's unclear which examples should stay, it's all or nothing I guess ..

**Comment by phated** [comment]
I'd be more than willing to give technical feedback on a full rewrite.  I might even be able to rope @janiceilene in for general content editing.

Do you want to take that on?  I think it'd probably be best to rewrite them all, then during review, I can decide if I don't like the recipe existing and then we can delete it.

**Comment by S1SYPHOS** [comment]
I'll look into it and whip something up.

**Comment by phated** [comment]
@s1syphos looks like you are no longer going to contribute these?

**Pull request closed without merging**
