### PR TITLE
Document plugin AP

### PR DESCRIPTION
**Pull request by nalbion**
This is my initial draft of additional documentation as discussed in #962.  At the moment, a lot of this is me thinking "out loud", but it may be helpful to others.

### CODE REVIEW

**Comment by nalbion** [comment]
I think that the main thing that was throwing me is that a lot of the plugins call `return callback(err,data);` - but my plugin needs to be asynchronous, so having to return anything immediately is not possible, and it's not obvious what the return value is.

...Upon further investigation it seems that callback() returns void, so it's just a short way of writing:

```
  callback(err,data);
  return;
```

**Comment by contra** [comment]
Nicely done - yeah callback can be called at any time so it doesn't matter if your code is asynchronous or synchronous, just call it when you are ready

**Comment by nalbion** [comment]
When I execute my gulp plugin:

```js
gulp.task('test', function() {
  gulp.src('test.js')
         .pipe(require('my-plugin')())
         .pipe(gulp.dest('output.js'));
});
```

Gulp passes me a Buffer.  Under what circumstances would it pass a Stream?

**Comment by nalbion** [comment]
Is

```js
   this.emit('error', new PluginError(PLUGIN_NAME, 'Streams not supported!'));
   callback();
   return;
```

equivalent to

```js
   callback(new PluginError(PLUGIN_NAME, 'Streams not supported!'));
   return;
```

?

**Comment by contra** [comment]
@nalbion It will pass a stream when you say `{buffer: false}` to src, useful for dealing with large files (lets say a 4GB video file) when your computer only has 1gb of ram

**Comment by nalbion** [comment]
If you set `src: 'http://example.com/testfile.js'` would it give you a Buffer or a Stream?

**Comment by contra** [comment]
@nalbion That doesn't exist and wouldn't work...

**Comment by nalbion** [comment]
Is

   this.emit('error', new PluginError(PLUGIN_NAME, 'Streams not supported!'));
   callback();
   return;
equivalent to

   callback(new PluginError(PLUGIN_NAME, 'Streams not supported!'));
   return;
?

**Comment by contra** [comment]
@nalbion depends on what module you're using, but in through2 yes

**Comment by phated** [comment]
Thanks for all the work on this.  Great guide!

**Pull request merged**
