### PR TITLE
Add glob-stream, node-glob docs to API docs

### PR DESCRIPTION
**Pull request by doug-wade**
[1281](https://github.com/gulpjs/gulp/issues/1281)

I erred on the side of including too many options instead of too few, to make reviewing easier -- all of them are included here that are supported, so you shouldn't have to open the docs -- so likely we'll want to prune them.  I'd say all the cache reuse stuff (symlinks, statCache, and buffer), and all the "don't include this glob feature" options (who doesn't like more features 😀) at least should be removed.

I didn't include any of the references to node-glob, since I don't think we want to leak implementation details from _our_ dependencies, since they can be changed in a semver patch release, and all our dependencies are caret ranges, but it does add a lot of weight to the gulp.src docs; we may want to remove a lot of the glob primer.

Sorry the diffs a little noisy -- alphabetizing the options simultaneously made it easier to write, but harder to review.

### CODE REVIEW

**Comment by doug-wade** [comment]
I poked around the failing build on 0.10.x -- it's failing with linting errors due to conflicts in how strict mode is handled, but I didn't touch bin/gulp?  Is there some way to kick of another build, to check if this is a transient failure?  Or did I actually break something?

**Comment by stevemao** [comment]
This should be done automatically by a build script.

**Comment by ilanbiala** [comment]
Any progress on this?

**Comment by contra** [comment]
Yeah, we can ignore the tests - something is whack with the linting lately. LGTM. @phated?

**Comment by contra** [comment]
I'm starting to think we should break the docs apart and use something like gitbook to generate the webpage

**Comment by phated** [comment]
@contra are you not interested in using readme.io anymore?

**Comment by contra** [comment]
@phated I think not, having to manually write the docs + them not being editable by the community is a dealbreaker. We can make a custom skin + plugins for gitbook just as easily.

**Comment by contra** [comment]
Here's an example gitbook auto-create setup I made:

- System: https://github.com/shastajs/palisade/blob/master/package.json#L40-L43
- Output: http://shasta.tools/palisade/

On any version bump it will create new docs and publish them to gh-pages

**Comment by doug-wade** [comment]
@contra should I close the pr since we're going to migrate to gitbook, which afaict would move the docs into a separate repo altogether and make this obsolete?  Or would it make sense to merge these changes and consider a different doc solution separately?  I _personally_ prefer to have my docs as close as possible to the code that they document -- ideally as doc strings at the method level, but at least in the same file and definitely in the same repo -- since it makes it easier to remember to update the docs when you're changing the code, but kinda feel like that discussion belongs in an issue rather than this pr (and also that I don't have a lot of the necessary context to contribute helpfully :stuck_out_tongue_winking_eye:).

**Comment by phated** [comment]
I'm going to close this, as we should implement an automated way using a plugin in gitbook that fetches a markdown file from github and clips out a section based on a header.

**Pull request closed without merging**
