### PR TITLE
i18n 和 L10n 

### PR DESCRIPTION
**Pull request by xgqfrms-GitHub**
zh-CN :cn: @gulp
Chinese translate version

### CODE REVIEW

**Comment by xgqfrms-GitHub** [comment]
what's wrong with this?

**Comment by neilhem** [comment]
l16n? Seems like typo, should be l11n

**Comment by xgqfrms-GitHub** [comment]
> l16n? Seems like typo, should be l11n

sorry for that mistake!  @neilhem 

Update: 
**i18n && L10n**
[https://www.w3.org/International/questions/qa-i18n](https://www.w3.org/International/questions/qa-i18n)

**Comment by xgqfrms-GitHub** [comment]
i18n 和 L10n

**Pull request closed without merging**
