### PR TITLE
add gitter badge and rearrange badge line

### PR DESCRIPTION
**Pull request by geekflyer**
* rearranged the badges so that everything still fits in one line.

### CODE REVIEW

**Comment by contra** [comment]
Is anyone actually using our gitter? I closed the last PR to add a badge because it wasn't useful

**Comment by geekflyer** [comment]
Well, as long as there's no link to it not many people will use it :grinning: . Just know some other projects like `6to5` , `systemjs`, `webpack` where the gitter room is really active (and they've linked it on their readme).

**Comment by contra** [comment]
sure we can give it a try. personally i dislike it because of the insane email notification preferences

**Comment by stringparser** [comment]
yeah, the defaults are quite insane but you can disable them either by writing [/lurk](https://gitter.zendesk.com/hc/en-us/articles/200227021-Lurk-mode) or preferences

**Pull request merged**
