### PR TITLE
Update using-multiple-sources-in-one-task.md

### PR DESCRIPTION
**Pull request by hiddentao**
* Added documentation on how to do order the merged stream

### CODE REVIEW

**Comment by TrySound** [comment]
@hiddentao It can be realized without dependencies by native Promises.
```
gulp.task('name', function () {
  return Promise.all([
    gulp.src('src1'),
    gulp.src('src2')
  ]);
});
```

**Comment by hiddentao** [comment]
@TrySound Don't really understand, please explain. `Promise.all` waits until all promises have finished executing - it has no implications regarding the order of execution. Plus, I'm really trying to merge two streams which both output files and I want to merge the streams (and thus process each file) in a specific order.

**Comment by callumacrae** [comment]
Streams aren't promises. Also, node.js doesn't have native promises yet, and not that people use iojs yet.

**Comment by phated** [comment]
We aren't supporting event-stream anymore, as it doesn't always use real streams.  `ordered-merge-stream` uses it as a dependency.  I'd be willing to support a PR like this with a better library suggested.

**Pull request closed without merging**
