### PR TITLE
refactor version for tasks compose

### PR DESCRIPTION
**Pull request by zensh**
Hi, @callumacrae
I have removed [standard](https://github.com/feross/standard) coding style as https://github.com/gulpjs/gulp/pull/1462.
It is now less changes.

What I bring to gulp here:

### support five task type:
1. sync task;
2. callback task;
3. promise task;
4. stream task;
5. generator task(async/await task later);

Here is generator task will like be:
```js
gulp.task('generator_task', function *() {
  yield somePromise;
  yield someThunk;
  yield gulp.all('a', 'b', 'c');
  yield gulp.seq('e', 'f', 'g');
  yield gulp.co('h', 'i', ['g', 'k'], 'l');
  // others ...
});
```

### gulp.start('task1', 'task2', ...[, cb])
Run tasks in order. Return thunk function.

```js
// Run 'default' task
gulp.start();
// Run 'default' task with callback
gulp.start(cb);
gulp.start()(cb);

// Run tasks 'a', 'b', 'c' in sequence
gulp.start('a', 'b', 'c');
// with callback
gulp.start('a', 'b', 'c', cb);
gulp.start('a', 'b', 'c')(cb);

// Run tasks 'a', 'b', 'c' in parallel
gulp.start(['a', 'b', 'c']);
// with callback
gulp.start(['a', 'b', 'c'], cb);
gulp.start(['a', 'b', 'c'])(cb);

// Run tasks 'a', then run 'b', 'c' in parallel, then run 'd'
gulp.start('a', ['b', 'c'], 'd');
// with callback
gulp.start('a', ['b', 'c'], 'd', cb);
gulp.start('a', ['b', 'c'], 'd')(cb);
```

### gulp.co('task1', 'task2', ...)
Compose tasks in order. It return thunk function that contain the tasks. The tasks will not run until you call the thunk function.

```js
// Compose tasks 'a', 'b', 'c', tasks will run in sequence
gulp.co('a', 'b', 'c');
// Compose tasks 'a', 'b', 'c', tasks will run in parallel
gulp.co(['a', 'b', 'c']);
// Compose tasks 'a', 'b', 'c', task 'a' will run first, then 'b', 'c' in parallel, then 'd'.
gulp.co('a', ['b', 'c'], 'd');
```

Define a task with `gulp.co`
```js
gulp.task('build', gulp.co('a', ['b', 'c'], 'd'));
// run it
gulp.start('build');
```

### gulp.all('task1', 'task2', ...)
Compose tasks in parallel. It return thunk function that contain the tasks. The tasks will not run until you call the thunk function.

```js
// Compose tasks 'a', 'b', 'c', tasks will run in parallel
gulp.all('a', 'b', 'c');
gulp.all(['a', 'b', 'c']);
```

Define a task with `gulp.all`
```js
gulp.task('build', gulp.all('a', 'b', 'c'));
// run it
gulp.start('build');
```

### gulp.seq('task1', 'task2', ...)
Compose tasks in sequence. It return thunk function that contain the tasks. The tasks will not run until you call the thunk function.

```js
// Compose tasks 'a', 'b', 'c', tasks will run in sequence
gulp.seq('a', 'b', 'c');
gulp.seq(['a', 'b', 'c']);
```

Define a task with `gulp.seq`
```js
gulp.task('build', gulp.seq('a', 'b', 'c'));
// run it
gulp.start('build');
```

### CODE REVIEW

**Comment by phated** [comment]
This is a complete rewrite that doesn't follow anything we've done in gulp4.  What is the point?

**Comment by zensh** [comment]
@phated It is full back compatibility with gulp v3. People don't need to rewrite gulpfile.js for updating to this version

**Comment by contra** [comment]
@zensh Have you looked at the new task API for gulp 4?

**Comment by zensh** [comment]
@contra It is why I refactor gulp. I hope to implement gulp v4' future(compose tasks) and back compatibility with gulp v3

**Comment by zensh** [comment]
I make our all build system with gulp v3 https://github.com/teambition/gulp-sequence.
With this version, I don't need change any code to run build tasks.And I can use `gulp.co` to instead of gulp-sequence also.

**Comment by zensh** [comment]
Could you accept this version as v3.10.x?

**Comment by phated** [comment]
I don't think we can accept this.  You say it is backward compatible with gulp 3.x but our tests are just smoke tests because we rely on orchestrator's test suite to dictate compatibility.  I don't think we can accept a PR with as sweeping changes as these and try to minor bump.  Sorry.

**Comment by zensh** [comment]
Got it. Thank you for your reply

**Comment by zensh** [comment]
I guessed your guys would not accept it. So I did't add more test cases. I just tested it in our productions.

**Pull request closed without merging**
