### PR TITLE
suggesting a cleaner way

### PR DESCRIPTION
**Pull request by asfktz**
found it on:
https://medium.com/@sogko/gulp-browserify-the-gulp-y-way-bb359b3f9623

### CODE REVIEW

**Comment by contra** [comment]
This is going to create a bundle for every js file in the folder, I don't think that is what users are expecting

**Comment by asfktz** [comment]
Absolutely right. Fixed.

**Comment by contra** [comment]
@phated Thoughts? This is a lot cleaner IMO

**Comment by phated** [comment]
:+1: I love vinyl-transform. It's like @hughsk's successor to the other vinyl-* modules he made. Even buffers by default. I think this should be the defacto way we promote using existing modules. Can you add a note to the top referencing the blog post?

**Comment by contra** [comment]
Cool I'm +1 to merge this. If you see any other docs using vinyl-buffer feel free to update those as well!

**Comment by asfktz** [comment]
I tried to make it work with the watchify example but with not success, can't figure way.. 

```js
var gulp = require('gulp');
var $ = require('gulp-load-plugins')();
var gutil = require('gulp-util');
var sourcemaps = require('gulp-sourcemaps');
var transform = require('vinyl-transform');
var watchify = require('watchify');
var browserify = require('browserify');

var bundler = watchify(browserify('./src/app.js', watchify.args));
// add any other browserify options or transforms here
//bundler.transform('brfs');

gulp.task('js', bundle); // so you can run `gulp js` to build the file
bundler.on('update', function (aa) {
    console.log(aa);
    bundle();
}); // on any dep update, runs the bundler

function bundle() {
    var bundled = transform(function () {
        return bundler.bundle();
    });

    return bundled
        // log errors if they happen
        .on('error', gutil.log.bind(gutil, 'Browserify Error'))
        .pipe(source('bundle.js'))
        // optional, remove if you dont want sourcemaps
        .pipe(buffer())
        .pipe(sourcemaps.init({
            loadMaps: true
        }))
            .pipe($.react({harmony: true}))
            //.pipe($.uglify())
        // loads map from browserify file
        .pipe(sourcemaps.write('./')) // writes .map file
        //
        .pipe(gulp.dest('./dist'));
}
```

**Comment by moimikey** [comment]
@contra @asfktz that `getBundleName` named func should probably get 86ed too.

**Comment by callumacrae** [comment]
Doesn't this read the JS file from disk twice?

**Comment by TomFrost** [comment]
@callumacrae is dead on the nose. My compile time is greatly reduced by changing

    return gulp.src('./app.js')

to

    return gulp.src('./app.js', {read: false})

at his suggestion.  Resulting file is the same. My version: https://github.com/TechnologyAdvice/Jexl/blob/master/gulpfile.js

**Pull request merged**
