### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### gulpjs/gulp now has a Chat Room on Gitter

@contra has just created a chat room. You can visit it here: [https://gitter.im/gulpjs/gulp](https://gitter.im/gulpjs/gulp?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/gulpjs/gulp?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by ilanbiala** [comment]
@contra can we merge this so everybody knows about it?

**Comment by contra** [comment]
Do people actually want to use this?

**Comment by arthurvr** [comment]
@contra Personally I don't.

**Comment by ilanbiala** [comment]
I was under the assumption that @contra or another core member set this up, I thought it was already gonna happen so might as well accept it...I'm not really for/against it.

**Comment by contra** [comment]
I set it up to try it out, I don't think it solves a problem we have though

**Comment by ilanbiala** [comment]
Gotcha, what was the problem?

**Comment by samccone** [comment]
this has been a huge win for us over at https://gitter.im/marionettejs/backbone.marionette/

community++

**Pull request closed without merging**
