### PR TITLE
Add recipe for bump version number and create a new Git tag

### PR DESCRIPTION
**Pull request by carpasse**

### CODE REVIEW

**Comment by phated** [comment]
I had to rebase the interpret commit, can you rebase your commits off the new master? thanks

**Comment by carpasse** [comment]
I have sync my repository. Is that all you need?

**Comment by heikki** [comment]
@carpasse http://stackoverflow.com/questions/17182624/contributing-to-project-on-github-how-to-rebase-my-pull-request-on-top-of-mast

**Comment by carpasse** [comment]
rebase done.

**Comment by contra** [comment]
Can you rebase?

**Comment by carpasse** [comment]
done

**Pull request merged**
