### PR TITLE
Fix rule numbers

### PR DESCRIPTION
**Pull request by tamj0rd2**
At the moment, rule numbers are showing as 1, 1, 1... etc

### CODE REVIEW

**Comment by contra** [comment]
@tamj0rd2 Are these not rendering correctly? According to the github markdown spec the # doesn't matter, so using 1 repeatedly is best to ensure they always increment and don't become unordered

**Comment by phated** [comment]
That's how it's supposed to work but it looks like they change or broke their parser (I'm seeing this problem everywhere someone mentions using 1 repeated).  @contra do you think we should merge this or wait to see if github fixes the bug (assuming it's not an intentional change).

**Comment by phated** [comment]
It seems that github did change their parser a while back (as per https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown and https://githubengineering.com/a-formal-spec-for-github-markdown/).  @tamj0rd2 Can you open an issue on https://github.com/github/cmark to see if this is a breaking change they intended before we merge this?

**Comment by tamj0rd2** [comment]
@doowb Thanks for spotting that. I've updated my commit.

**Comment by phated** [comment]
Thanks!!

**Pull request merged**
