### PR TITLE
Add is it maintained badges

### PR DESCRIPTION
**Pull request by jpventura**
Details
---------
[Is it maintained?][1] is an open source project whose goal is to monitor open source projects, certifying how well it is maintained.

The metrics are:

| Metric                                                           | Description                          |
|------------------------------------------------------------------|--------------------------------------|
| [![Issue resolution][resolution-time-image]][isitmaintained-url] | Median time needed to close an issue |
| [![Open issues][open-percentage-image]][isitmaintained-url]      | Percentage of open issues            |

Some issues are ignored based on their labels (example of ignored labels: "enhancement", "feature"…). For the median time needed to close an issue, issues older than 6 months are ignored too.

References
---------------

  - [IS IT MAINTAINED? Check the activity of open source projects][1]

[1]: https://isitmaintained.com/#about
[isitmaintained-url]: https://isitmaintained.com/project/gulpjs/gulp
[open-percentage-image]: https://isitmaintained.com/badge/open/gulpjs/gulp.svg
[resolution-time-image]: https://isitmaintained.com/badge/resolution/gulpjs/gulp.svg

### CODE REVIEW

**Comment by jpventura** [comment]
Strange... only `README.md` file was modified, thus the build should not fail :thinking:

**Comment by contra** [comment]
Are these metrics useful to people looking at a project? I don't think issue resolution time or % of open issues is a great indicator of a project being maintained or not, even though our numbers are good (seems to be the best out of the "Popular Projects" on the homepage).

Curious what others have to say about this - FWIW I have always taken pride in responding to issues quickly across all of my projects, just not sure of the utility besides bragging rights.

**Comment by phated** [comment]
I often find issues with these metrics because a project might use issues to get feedback, or leave issues open that need to be solved much further in the future. Anyway, just my 2 cents.

**Comment by phated** [comment]
Also, a lot of the gulp work happens in any of our 40+ other repos, so this metrics on this repo don't tell us much.

**Comment by phated** [comment]
I'm going to close this because I don't think it is needed.

**Pull request closed without merging**
