### PR TITLE
Created recipe to show how to copy files

### PR DESCRIPTION
**Pull request by gortok**
This addresses a common question I see with Gulp (with SEO Friendly terms) and also brought up in issue #284.

### CODE REVIEW

**Comment by callumacrae** [comment]
-1, this will say that it is finished before it is done. the streams should be combined if you're going to do this

**Comment by gortok** [comment]
@callumacrae After your helpful comment, I looked up the stream-combiner2 as a way to do this; but unfortunately the following code errors whenever you try to pass more than one src function to it that writes to the same location with a `write after end` error.

```js
gulp.task('move-statics', function () {
  var combined = combiner.obj([
    gulp.src('static/html/robots.txt')
      .pipe(gulp.dest('dist')),
    gulp.src('static/images/favicon.*')
      .pipe(gulp.dest('dist')),
    gulp.src('static/images/**')
      .pipe(gulp.dest('dist/assets/images'))
  ]);
  return combined;
});
```

From what I see from your activity, you seem to know gulp a great deal better than I do; can you suggest an improvement or how I could implement your suggestion?

**Comment by KapuzenSohn** [comment]
For copieng Files I use something like this:
``` javascript
gulp.task('copy:images', function() {
  gulp.src(['src/**/[i|I]mg/**/*.*', 'src/**/[i|I]mages/**/*.*']) // ['file one', 'file two', 'file three', '...']
  .pipe(gulp.dest('dist'));
});
```

**Comment by gortok** [comment]
@KapuzenSohn That's really interesting, but it doesn't cover the specific use-case I'm targeting: when you want to copy files to different places.  Could you show me the preferred way to do that?  It doesn't appear like my initial approach is appropriate (h/t to @callumacrae).

**Comment by KapuzenSohn** [comment]
Oh, I see. I would combine the ```static/html/robots.txt``` and ```static/images/favicon.*´`` to a single gulp.src like I have and the other one should stay like you currently have.

Tahts the only solution I currently have. I looked at my Gulpfiles but I don´t have a similar problem.

**Comment by callumacrae** [comment]
@gortok Check out this recipe: https://github.com/gulpjs/gulp/blob/master/docs/recipes/using-multiple-sources-in-one-task.md

The thing you're using is one of the other recipes, so that you can handle errors from all plugins in a task with the same handler.

**Comment by phated** [comment]
I don't think we need this, as it is addressed in the recipe @callumacrae linked and shows how to correctly signal task completion.  @gortok If you would like to add some description/context to the linked recipe, I'll take a look at that PR.

**Pull request closed without merging**
