### PR TITLE
Docs: Clarify CLI semantics when listing more than one task

### PR DESCRIPTION
**Pull request by kylecordes**
This clarifies the semantics brought up in #1915 and makes a tiny bit of progress on #1595

### CODE REVIEW

**Comment by contra** [comment]
We should add this to our 4.0 docs as well - @phated ?

**Comment by kylecordes** [comment]
This comes to mind, it might be worth considering: 4.0 is a substantial change anyway. It's getting rid of sync tasks, which can be currently used (as I do) to do something like 'gulp clean dist' and have it work. Since that is going away, perhaps also the semantic of the CLI could change, to execute the tasks sequentially. An option could be added to get the old behavior (which does have its uses) of executing the tasks as siblings.

**Comment by phated** [comment]
It needs to be submitted to the `gulp-cli` readme since that's where the CLI has moved.

**Comment by kylecordes** [comment]
@phated  https://github.com/gulpjs/gulp-cli/pull/105

**Pull request merged**
