### PR TITLE
Update server-with-livereload-and-css-injection.md

### PR DESCRIPTION
**Pull request by pensierinmusica**
Browsersync offers an updated API for injecting CSS, as shown in their docs: http://www.browsersync.io/docs/gulp/

### CODE REVIEW

**Comment by shinnn** [comment]
@shakyShane I'd like you to review this.

Or, this markdown file can be replaced with a simple link instead of having almost the same recipes in those two different projects.

**Comment by callumacrae** [comment]
I think that's a no!

Honestly, I can't see the point in this recipe; it seems redundant with the instructions on the browser-sync website. Could just replace it with a link to their docs? Anyone else have thoughts?

**Comment by phated** [comment]
I would love to offload any and all recipes to the docs in their respective libraries so I agree with @callumacrae - closing this in favor of replacing the recipe with a link to http://www.browsersync.io/docs/gulp/

**Comment by shakyShane** [comment]
There's also a bunch of our own working recipes https://github.com/BrowserSync/recipes

**Pull request closed without merging**
