### PR TITLE
chore: update graceful-fs to v4.0.0

### PR DESCRIPTION
**Pull request by MylesBorins**
Test suite is broken on Node master with graceful-fs 3.x

### CODE REVIEW

**Comment by phated** [comment]
Do you know where graceful-fs is used in the test suite?  Does it make more sense to just switch to `fs`?  If we have watch tests, those likely will continue to fail.

**Comment by MylesBorins** [comment]
This is not 100% necessary right now. A patch was floated in natives to keep things working on graceful fs 3.x... that being said there are likely silent errors on Node.js 8.x + with graceful fs > 4

**Comment by MylesBorins** [comment]
opened https://github.com/gulpjs/gulp/pull/2057 as an alternative that simply removes graceful-fs as a direct dev dep

**Comment by phated** [comment]
@MylesBorins by "there are likely silent errors on Node.js 8.x + with graceful fs > 4" do you mean that the latest graceful-fs is being broken by node 8?

**Comment by MylesBorins** [comment]
@phated I mean that graceful >= 3.x is deprecated and relies on apis that are unsupported on Node.js 8.x +

**Comment by phated** [comment]
Oh, okay.  I was guessing it was a typo and was supposed to be "< 4" instead of "> 4"

Thanks for clarifying.

**Comment by MylesBorins** [comment]
ugh ya... I totally type oed both of those... sigh

**Comment by phated** [comment]
All good. I just wanted to make sure since I shipped a major of vinyl-fs yesterday with graceful-fs 4.x 😛

**Comment by MylesBorins** [comment]
Closing in lieu of https://github.com/gulpjs/gulp/pull/2057

**Pull request closed without merging**
