### PR TITLE
Fix old code

### PR DESCRIPTION
**Pull request by tyscorp**
According to npm statistics, 0.01% of node.js users are still using 0.10. I think it's now safe to update the codebase a bit to reflect the community.

Thanks!

### CODE REVIEW

**Comment by terinjokes** [comment]
At this time, since several distributions are still shipping Node.js 0.10, we're continuing to support this version.

**Comment by phated** [comment]
Those are straight incorrect numbers.  Also, if you think that littering your code with arrow functions is helping, you should think again.

**Comment by phated** [comment]
Non-bullshit numbers from https://twitter.com/seldo/status/781258069678391296

> Node 0.10 still has 13% share; don't drop support yet.

node10_sep_16

**Comment by callumacrae** [comment]
"Fix" old code? Was it broken?

Fat arrow functions are less likely to be understood by junior developers or people who don't know ES6. This isn't just about Node 0.10, this is about understandable and accessible code, too. I notice you've left the documentation alone, though.

**Pull request closed without merging**
