### PR TITLE
Fix source maps usage by replacing gulp-sourcemaps with debug:true brows...

### PR DESCRIPTION
**Pull request by airandfingers**
...erify option

Fixes https://github.com/gulpjs/gulp/issues/981

### CODE REVIEW

**Comment by contra** [comment]
No reason to get rid of gulp-sourcemaps, just the option change will fix this

**Comment by terinjokes** [comment]
Furthermore, keeping the `gulp-sourcemaps` usage ensures gulp plugins down stream properly handle the source maps.

**Comment by airandfingers** [comment]
I haven't tested this with gulp-sourcemaps, since I already had source maps working. Feel free to modify this (or tell me how to modify it).

**Comment by phated** [comment]
We wanted to keep gulp-sourcemaps and stuff so I've rewritten the watchify recipe in https://github.com/gulpjs/gulp/commit/7176929f09905cc2e7a2bb93f53779b54c081536

I've also tested and verified it is working as expected.  Thanks for pushing this forward.

**Pull request closed without merging**
