### PR TITLE
Simplify browserify-transforms.md

### PR DESCRIPTION
**Pull request by mikemaccana**
Specify full name of output explicitly
Remove unused reactify code
Tighten

### CODE REVIEW

**Comment by callumacrae** [comment]
Pretty sure the reactify stuff was half the point of this fiel

**Comment by mikemaccana** [comment]
@callumacrae Text at top doesn't mention reactify at all. Unless the purpose of the demo is changed - it's better to keep the example focused on browserify.

**Comment by jmm** [comment]
@mikemaccana I think you've inadvertently revealed that there's no reason for this document to exist anymore. With these changes I think it's just [Browserify + Uglify2 with sourcemaps](https://github.com/gulpjs/gulp/blob/master/docs/recipes/browserify-uglify-sourcemap.md).

**Comment by mikemaccana** [comment]
@jmm *looks* Yup.

**Comment by jmm** [comment]
@callumacrae @mikemaccana The point of the reactify part was that this recipe used to show a broken technique using `vinyl-transform` and placement of the transform registration code was significant. Then that whole technique was eliminated from the document.

**Comment by jmm** [comment]
@mikemaccana So I would suggest to instead PR to remove this document, or change the name and turn it into a completely minimal gulp+browserify recipe without source maps and uglify.

**Comment by mikemaccana** [comment]
*nod* will do

**Pull request closed without merging**
