### PR TITLE
Linting - few extra commas

### PR DESCRIPTION
**Pull request by jasonwr**
Minor edits

### CODE REVIEW

**Comment by phated** [comment]
Oops, this is per our linting rules.  Reverting.

**Comment by jasonwr** [comment]
Can you explain? Extra commas at the end of an array aren't necessary and need to be linted!

**Comment by jasonwr** [comment]
Can you explain? Extra commas at the end of an array aren't necessary and
need to be linted!

On Thu, Jun 30, 2016 at 4:55 PM, Blaine Bublitz <notifications@github.com>
wrote:

> Oops, this is per our linting rules. Reverting.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gulpjs/gulp/pull/1709#issuecomment-229785953>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AASrT5RCMb4EXHhYDwxw-u0JBI4wqdXPks5qRC0_gaJpZM4JCSau>
> .
>



-- 
Jason W. Rice
LinkedIn:http://www.linkedin.com/pub/jason-rice/16/10/131/
Email:jsnrice@gmail.com

**Comment by phated** [comment]
Trailing commas are an ES5 feature and suggested in node-style-guide, which is why we use them.

**Comment by jasonwr** [comment]
No way! Why are they suggested in the node style guide? Netbeans IDE is
telling me they are evil.

On Thu, Jun 30, 2016 at 5:18 PM, Blaine Bublitz <notifications@github.com>
wrote:

> Trailing commas are an ES5 feature and suggested in node-style-guide,
> which is why we use them.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gulpjs/gulp/pull/1709#issuecomment-229791620>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AASrT0aIqEr3-cGmO5TlH1kUpUqbg2gZks5qRDKJgaJpZM4JCSau>
> .
>



-- 
Jason W. Rice
LinkedIn:http://www.linkedin.com/pub/jason-rice/16/10/131/
Email:jsnrice@gmail.com

**Comment by jasonwr** [comment]
@phated No way! Why are they suggested in the node style guide? Netbeans IDE is telling me they are evil.

**Comment by jasonwr** [comment]
@phated No way! Why are they suggested in the node style guide? Netbeans IDE is telling me they are evil.

**Comment by phated** [comment]
@jasonwr it sounds like your editor doesn't apply our eslintrc file.  Sorry, it's proper JS.

**Comment by jasonwr** [comment]
@phated hm.. alrighty.

**Pull request merged**
