### PR TITLE
added link to "Cross Platform Builds with gulp - Build as a Service"

### PR DESCRIPTION
**Pull request by ThorstenHans**

### CODE REVIEW

**Comment by phated** [comment]
I think we need to wait on this. Gulp 4 is close to release and lots of the information in the post is gulp 3 specific.

**Comment by ThorstenHans** [comment]
are the docs in 4.0 already updated?

**Comment by phated** [comment]
@ThorstenHans yeah, we have to port some of the new recipes but everything else has been updated

**Comment by phated** [comment]
Closing this as per my comments above.

**Pull request closed without merging**
